### ISSUE TITLE
Plugin doesn't work on digdag v0.10.0

### ISSUE THREAD

**Issue by yackrru** [takemikami/digdag-plugin-shresult#4]
Thank you for the plugin.

## Purpose
- Plugin doesn't work on digdag v0.10.0
- On v0.10.0, `CommandExecutor.start()` have been abolished ([commit diff](https://github.com/treasure-data/digdag/commit/e17ad5b6263a820015a17d49cce6eea8f3f62e9f)).
https://github.com/takemikami/digdag-plugin-shresult/blob/d6d6496c4b631e5662b7328029c68c0c033c137b/src/main/java/com/takemikami/github/digdag/plugin/shresult/ShResultOperatorFactory.java#L103

<details>
<summary>Error log</summary>

```bash
2021-02-15 02:53:26.732 +0000 [INFO] (0363@[0:test2]+file_check+task) io.digdag.core.agent.OperatorManager: sh_result>: ls /tmp
2021-02-15 02:53:26.809 +0000 [ERROR] (0363@[0:test2]+file_check+task) io.digdag.core.agent.OperatorManager: Task failed with unexpected error: io.digdag.spi.CommandExecutor.start(Ljava/nio/file/Path;Lio/digdag/spi/TaskRequest;Ljava/lang/ProcessBuilder;)Ljava/lang/Process;
java.lang.NoSuchMethodError: io.digdag.spi.CommandExecutor.start(Ljava/nio/file/Path;Lio/digdag/spi/TaskRequest;Ljava/lang/ProcessBuilder;)Ljava/lang/Process;
	at com.takemikami.github.digdag.plugin.shresult.ShResultOperatorFactory$ShResultOperator.runTask(ShResultOperatorFactory.java:103)
	at io.digdag.util.BaseOperator.run(BaseOperator.java:35)
	at io.digdag.core.agent.OperatorManager.callExecutor(OperatorManager.java:365)
	at io.digdag.server.metrics.DigdagTimedMethodInterceptor.invokeMain(DigdagTimedMethodInterceptor.java:58)
	at io.digdag.server.metrics.DigdagTimedMethodInterceptor.invoke(DigdagTimedMethodInterceptor.java:31)
	at io.digdag.core.agent.OperatorManager.runWithWorkspace(OperatorManager.java:298)
	at io.digdag.server.metrics.DigdagTimedMethodInterceptor.invokeMain(DigdagTimedMethodInterceptor.java:58)
	at io.digdag.server.metrics.DigdagTimedMethodInterceptor.invoke(DigdagTimedMethodInterceptor.java:31)
	at io.digdag.core.agent.OperatorManager.lambda$runWithHeartbeat$2(OperatorManager.java:151)
	at io.digdag.core.agent.ExtractArchiveWorkspaceManager.withExtractedArchive(ExtractArchiveWorkspaceManager.java:77)
	at io.digdag.core.agent.OperatorManager.runWithHeartbeat(OperatorManager.java:149)
	at io.digdag.server.metrics.DigdagTimedMethodInterceptor.invokeMain(DigdagTimedMethodInterceptor.java:58)
	at io.digdag.server.metrics.DigdagTimedMethodInterceptor.invoke(DigdagTimedMethodInterceptor.java:31)
	at io.digdag.core.agent.OperatorManager.run(OperatorManager.java:132)
	at io.digdag.server.metrics.DigdagTimedMethodInterceptor.invokeMain(DigdagTimedMethodInterceptor.java:58)
	at io.digdag.server.metrics.DigdagTimedMethodInterceptor.invoke(DigdagTimedMethodInterceptor.java:31)
	at io.digdag.core.agent.MultiThreadAgent.lambda$null$0(MultiThreadAgent.java:132)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
</details>

## Proposal
- Migrate `CommandExecutor.start()` to `CommandExecutor.run()`
  - Changes on migration might be significantly expanded because I'm not as knowledgeable about this change.

## Problem Information
On digdag server v0.10.0, execute `RUN` after registering the following workflow.

<details>
<summary>workflow</summary>

```yaml
timezone: Asia/Tokyo

_export:
  workflow_name: file_check
  plugin:
    repositories:
    - https://jitpack.io
    dependencies:
    - com.github.takemikami:digdag-plugin-shresult:0.0.2

+task:
  sh_result>: ls /tmp
  destination_variable: files
  stdout_format: text
```
</details>

## TODOs
- [x] The plugin works fine on digdag server v0.10.0

**Comment by takemikami** [comment]
fix by #7, and digdag-plugin-shresult v0.0.3 support digdag v0.10.0.
